insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into clients(name, last_name, email, create_at, photo)values('Ricardo', 'Cardona', 'ricardo@gmail.com', '2019-10-05', '');
insert into clients(name, last_name, email, create_at, photo)values('Pedro', 'Dominguez', 'pedro@gmail.com', '2019-10-09', '');
insert into clients(name, last_name, email, create_at, photo)values('Daniel', 'Perez', 'daniel@gmail.com', '2019-10-07', '');
insert into products(name, price, create_at)values('PanasonicTV', 15000, NOW());
insert into products(name, price, create_at)values('LGTV', 12000, NOW());
insert into products(name, price, create_at)values('Vibe', 1000, NOW());
insert into products(name, price, create_at)values('Plancha', 300, NOW());
insert into products(name, price, create_at)values('Tostadora', 1000, NOW());
insert into products(name, price, create_at)values('LapB&D', 15000, NOW());
insert into bills(description, observation, client_id, create_at)values('Bill office things', null, 1, NOW());
insert into bill_items(quantity, bill_id, product_id)values(1, 1, 1);
insert into bill_items(quantity, bill_id, product_id)values(2, 1, 2);
insert into bills(description, observation, client_id, create_at)values('Bill xxx', null, 33, NOW());
insert into bill_items(quantity, bill_id, product_id)values(3, 2, 4);
insert into bill_items(quantity, bill_id, product_id)values(4, 2, 5);

insert into users(username, password, enabled)values('ricardo', '$2a$10$PKdpj7R3TFCwmmgyXD60We4AxdrjNKOqueI7GtGSbZWJ3tmMcNU3a', 1);
insert into users(username, password, enabled)values('admin', '$2a$10$0imdYfXijZBJW.8NBHYqZOecLWDj9ca3nHPxGyCts5SDa89mZcpBW', 1);

insert into authorities(user_id, authority)values(1, 'ROLE_USER');
insert into authorities(user_id, authority)values(2, 'ROLE_ADMIN');
insert into authorities(user_id, authority)values(2, 'ROLE_USER');
